# Generated by Django 3.2.6 on 2021-08-25 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Адрес')),
                ('numb', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['numb'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('brand', models.TextField(blank=True, verbose_name='Бренд')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('item', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Артикул')),
                ('shop', models.TextField(blank=True, verbose_name='Магазин')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_executed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.constructionsite', verbose_name='Объект')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='application.photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
